// Generated by CoffeeScript 1.7.1
(function() {
  var Telegram, map, sessions, tg, _;

  _ = require('lodash');

  Telegram = require('node-telegram-bot');

  tg = new Telegram('116265847:AAFfQunaAJyFl9gxoXk69OTi5zii2E1eDeg');

  sessions = {};

  map = {
    help: function(msg) {
      return {
        text: "/random - Gera um número random\n/help - Sobre a Ritsuko"
      };
    },
    random: function(msg) {
      var randomNumber;
      randomNumber = _.shuffle([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).slice(0, 4).join("");
      return msg.reply({
        text: "Número gerado é: " + {
          randomNumber: randomNumber
        }
      });
    }
  };

  tg.on('message', function(msg) {
    var cmd, text, _ref;
    console.log("" + msg.date + " " + msg.from.username + ": " + msg.text);
    text = String(msg.text).trim();
    msg.reply = function(options) {
      return tg.sendMessage(_.defaults(options, {
        reply_to_message_id: this.message_id,
        chat_id: this.chat.id
      }));
    };
    cmd = String((_ref = text.match(/^\/([a-zA-Z0-9]*)(@gaussbot)?/i)) != null ? _ref[1] : void 0).toLowerCase();
    if (cmd && map[cmd]) {
      return map[cmd](msg);
    }
    if (sessions[msg.chat.id]) {
      return sessions[msg.chat.id](msg);
    }
  });

  tg.start();

}).call(this);
